development: &development
  adapter: postgresql
  database: gift_your_time
  user: gift_your_time
  host: localhost
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  database: gift_your_time
  user: gift_your_time
  host: localhost
  pool: 5
  timeout: 5000


test: &test
  adapter: postgresql
  database: gift_your_time_test
  user: gift_your_time
  host: localhost
  pool: 5
  timeout: 5000

cucumber: <<test